unstable_features = true
reorder_imports = true
max_width = 80
imports_granularity = "Crate"
reorder_impl_items = true
group_imports = "One"
wrap_comments = true
brace_style = "AlwaysNextLine"
combine_control_expr = true
empty_item_single_line = true
enum_discrim_align_threshold = 40
error_on_unformatted = true
error_on_line_overflow = true
fn_args_layout = "Vertical"
fn_params_layout = "Vertical"
force_multiline_blocks = true
format_code_in_doc_comments = true
doc_comment_code_block_width = 60
format_strings = true
imports_layout = "Vertical"
match_arm_leading_pipes = "Always"
where_single_line = false
blank_lines_lower_bound = 0
blank_lines_upper_bound = 1
